### ISSUE TITLE
Ports

### ISSUE THREAD

**Issue by mattbroekhuis** [go-vela/docs-old#186] opened 2020-11-17 18:22 UTC
In my experience, you can't map the ports like "9080:8080"

Assuming that is correct, perhaps the docs could mention this.

**Comment by mattbroekhuis** [comment] 2020-11-17 18:22
https://go-vela.github.io/docs/concepts/pipeline/services/ports/

**Comment by susangreve** [comment] 2021-05-07 14:51
Duplicate of https://github.com/go-vela/community/issues/127 - closing

**Closed as completed by susangreve** 2021-05-07 14:51 UTC
