### ISSUE TITLE
Sample validation message isn't accurate

### ISSUE THREAD

**Issue by JoshuaShaffer1** [go-vela/docs-old#28] opened 2019-11-19 17:04 UTC
https://go-vela.github.io/docs/usage/reference/cli/validate/#sample

The actual message returned by my running of the command is:
`Config is valid.`

**Comment by kneal** [comment] 2019-11-20 15:48
Thanks for the catch! The issue is actually reversed though. We want the feedback to look like how it is in the docs. The main reason, is eventually we will add a flag to the `validate` command that lets you specify a path to a file. So, we would want the user to know the file they passed is the valid file.

I opened up a PR to fix the issue on the CLI. It will be fixed in the next CLI release.
https://github.com/go-vela/cli/pull/26

**Comment by kneal** [comment] 2019-12-02 15:29
Closing this one since we have a PR merged with the fix. Will circle back if it pops up again.

**Closed as completed by kneal** 2019-12-02 15:29 UTC
Labels: bug
